### Create a new user
POST http://localhost:3001/api/users
Content-Type:application/json
Accept: application/json

{
"username":"Nikola",
"name":"Nikola",
"password":"Nikola"
}
###Login
POST http://localhost:3001/api/login

{
"username": "Nikola",
"password": "Nikola"
}

### Add Parcel
POST http://localhost:3001/api/parcels
Content-Type:application/json
Authorization: bearer 

{
"name": "Nova",
"vrsta_useva": "Sljiva",
"povrsina": "1.2",
}

### Create activity of obrada type

POST http://localhost:3001/api/activities/obrada
Content-Type:application/json
Authorization: "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pa29sYSIsImlkIjoiNjdlNmY0Y2QyNzY4YzMyYmI5YmMyOGNiIiwiaWF0IjoxNzQzNzYyNDQ5fQ.50EgRRaJLM8_ZBVPSiNBIUMG8fXgXcZXYK44TbBplDQ"

    {
        "activityType": "obrada",
        "datum_od": "11-12-2024",
        "datum_do": "11-12-2024",
        "tip_obrade": "oranje",
        "parcel": "67e6f7f8e68483481acb1ad0"
    }

