### Create a new user
POST http://localhost:3001/api/users
Content-Type:application/json
Accept: application/json

{
"username":"Nikola",
"name":"Nikola",
"password":"Nikola"
}
###Login
POST http://localhost:3001/api/login

{
"username": "Nikola",
"password": "Nikola"
}

### Add Parcel
POST http://localhost:3001/api/parcels
Content-Type:application/json
Authorization: bearer 

{
"name": "Nova",
"vrsta_useva": "Sljiva",
"povrsina": "1.2",
}

### Create activity of obrada type "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pa29sYSIsImlkIjoiNjdlNmY0Y2QyNzY4YzMyYmI5YmMyOGNiIiwiaWF0IjoxNzQzNzYyNDQ5fQ.50EgRRaJLM8_ZBVPSiNBIUMG8fXgXcZXYK44TbBplDQ"

POST http://localhost:3001/api/activities/obrada
Content-Type:application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pa29sYSIsImlkIjoiNjdlNmY0Y2QyNzY4YzMyYmI5YmMyOGNiIiwiaWF0IjoxNzQ0MDE2MjUwfQ.Biiww4zJ3DFFoJPu4X4kNrP1C0OPzwZC64CUoyjbCfA"

    {
        "activityType": "obrada",
        "datum_od": "12-12-2024",
        "datum_do": "12-12-2024",
        "tip_obrade": "oranje",
        "parcel": "67e6f7f8e68483481acb1ad0"
    }


### Downlink to TTN example
POST  https://eu1.cloud.thethings.network/api/v3/as/applications/novappprroba/webhooks/proba-hook/devices/mojuredjajsafaksa/down/push
Content-Type:application/json
Authorization: "Bearer NNSXS.523DYXOLFLU5C25C5VYOUIVAJUF5CKDCSB6JWZY.ERBFIWIOA24ALXZFLKTTDRDJ7ADRA77VRK7WMOUMEIBHYBKEM4OQ" 

   {
  "end_device_ids" : {
    "device_id" : "mojuredjajsafaksa",                    // Device ID
    "application_ids" : {
      "application_id" : "novappprroba"              // Application ID
    }
  },
  "downlinks": [{
    "f_port": 1,                            // Frame port
    "frm_payload": "MTU=",                   // Frame payload (Base64)
    "priority": "NORMAL",                    // Priority of the message in the downlink queue
    "confirmed": true,                       // If the downlink expects a confirmation from the device or not
    "correlation_ids" : [  "as:downlink:01JRB8MYRJ77TC6PBCEH7ZBAQD" ]      // Correlation identifiers of the message
  }]
}


### Downlink to Meteoscientific
POST https://console.meteoscientific.com/api/devices/f2a14164e12277d6/queue
Content-Type:application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6ImVmMmI4YzcxLWJjNjMtNDExZi05Mzc3LTVlNmU2MjZiZTRiZCIsInR5cCI6ImtleSJ9.xV8q-KmRj5tYq-YInWJX9U9OdwR6-JoauXk8gRuzhWc"

{
    "queueItem": {
      "confirmed": true,
      "fPort": 28,
      "data": "AAUABQ==",
      "isEncrypted": false,
      "isPending": false,
      "fCntDown": 0,
      "expiresAt": null
    }
  }